### ISSUE TITLE
Surround arguments with ' in config file

### ISSUE THREAD

**Issue by anvandaren** [jesseduffield/lazycli#16]
Hi,

Just installed `lazycli` on Ubuntu 18.04 and tried it with `ls -l`. Operations for files that contain spaces does not work with the default config file as the argument is not surrounded by '. When I add that for example `rm` works. Example:
```
  - name: ls -l
    registered_commands:
      - ls -l
    key_bindings:
      - key: d
        command: rm -rf '$8'
        confirm: true
      - key: o
        command: xdg-open '$8'
      - key: u
        command: cd '$8'
    lines_to_skip: 1
```

Thanks!
